# Generated by Django 4.2.4 on 2024-05-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhoneProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ndc", models.IntegerField()),
                ("snA", models.DecimalField(decimal_places=2, max_digits=10)),
                ("snB", models.DecimalField(decimal_places=2, max_digits=10)),
                ("capacity", models.IntegerField(blank=True, null=True)),
                ("provider", models.TextField(blank=True, null=True)),
                ("region", models.TextField(blank=True, null=True)),
                ("territory_gar", models.TextField(blank=True, null=True)),
                (
                    "inn",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "db_table": "phone_providers",
                "indexes": [
                    models.Index(fields=["ndc", "snA", "snB"], name="idx_provider")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="phoneprovider",
            constraint=models.UniqueConstraint(
                fields=("ndc", "snA", "snB"), name="unique_ndc_snA_snB"
            ),
        ),
    ]
